version: "3.8"

services:
  bot:
    build: .
    container_name: sismobot
    restart: always
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./data:/app/data
